### ISSUE TITLE
Times that are "almost now" output incorrectly

### ISSUE THREAD

**Issue by deevus** [montanaflynn/human-date#9]
See here: https://codesandbox.io/s/mo4kvw5kq9

From my testing `humanDate.relativeTime(new Date().toString())` always outputs `" ago"`. `humanDate.relativeTime(new Date())` sometimes outputs `"now"` and sometimes outputs `" ago"`

My guess is that there is a bug in the library that occurs somewhere between "now" and "1 second ago"

**Comment by deevus** [comment]
In the following code, if `seconds` is less than 1, the floor will evaluate to `0`. However `seconds` is still not `0` as it is some value less than 1. 

You end up in a situation where `isPast` is true, `time.seconds` is false but `seconds !== 0` and so it outputs `" ago"` because all the time units are falsey. 

https://github.com/montanaflynn/human-date/blob/3e0de2646fbcfb8693fbd462ef9c31910b2f76c8/humandate.js#L66-L103

**Comment by deevus** [comment]
One solution might be to say if `time.{seconds, minutes, hours, days, years}` are all `0` then it's "Less than a second ago"

**Comment by montanaflynn** [comment]
I like the "Less than a second ago" idea, could you submit a PR or would you like me to?
